env:
  browser: true
  es2020: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:import/recommended'
  - 'plugin:import/typescript'
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
settings:
  import/resolver:
    node:
      extensions:
        - '.ts'
      moduleDirectory:
        - node_modules
        - src/
rules:
  prettier/prettier: error
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true
  semi:
    - error
    - always
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-empty-interface': off
